-- CREATE DATABASE SensorProject;
-- USE SensorProject;
-- 
-- CREATE TABLE Sensors (
--     SensorID INT PRIMARY KEY AUTO_INCREMENT,
--     SensorName VARCHAR(50) NOT NULL,
--     IsActive BOOLEAN DEFAULT TRUE,
--     Uses INT DEFAULT 0,
--     HasMatched BOOLEAN DEFAULT FALSE
-- );
-- 
-- CREATE TABLE IranianAgents (
--     AgentID INT PRIMARY KEY AUTO_INCREMENT,
--     AgentType VARCHAR(50) NOT NULL,
--     Weaknesses TEXT NOT NULL,
--     SensorAmount INT NOT NULL
-- );
-- 
-- CREATE TABLE MatchedWeaknesses (
--     MatchID INT PRIMARY KEY AUTO_INCREMENT,
--     SensorID INT,
--     AgentID INT,
--     WeaknessCount INT DEFAULT 0,
--     FOREIGN KEY (SensorID) REFERENCES Sensors(SensorID),
--     FOREIGN KEY (AgentID) REFERENCES Agents(AgentID)
-- );

-- CREATE TABLE People (
--   id INT PRIMARY KEY,
--   first_name VARCHAR(100),
--   last_name VARCHAR(100),
--   location VARCHAR(100),
--   favorite_weapon VARCHAR(100),
--   contact_number VARCHAR(50),
--   secret_phrase VARCHAR(100),
--   affiliation VARCHAR(100),
--   is_exposed BOOLEAN DEFAULT FALSE
-- );

-- CREATE TABLE Player (
--     id INT PRIMARY KEY AUTO_INCREMENT,
--     username VARCHAR(50) NOT NULL UNIQUE,
--     level INT NOT NULL DEFAULT 1
-- );
